### ISSUE TITLE
Sentry not working with Rails 4.2.5.1 ? (undefined method `[]=' for nil:NilClass)

### ISSUE THREAD

**Issue by vdaubry** [getsentry/raven-ruby#460]
When adding Sentry to a new Rails 4.2.5.1 project i get ``` undefined method `[]=' for nil:NilClass ``` after every exception

It makes stack traces harder to read, and worse : 404 errors such as routing errors turn into 500.

Here is a sample stack trace illustrating the problem : https://gist.github.com/vdaubry/b8be537646c4f3536bc8

Here is the list of gems (i only added sentry to a new rails project) :
https://gist.github.com/vdaubry/5511ef807134b3ee3e07

Steps to reproduce :
* Create a new rails 4.2.5.1 project
* Add sentry gem

Edit :
If i remove the ``` sentry-raven ``` gem the ``` undefined method `[]=' for nil:NilClass ``` disappears

**Comment by seanlinsley** [comment]
It looks like there's an incompatibility between web-console and raven-ruby.

There isn't really any need to run Raven in development. This is what I do in an initializer:
```ruby
case Rails.env
when 'production', 'staging'
  require 'raven'

  Raven.configure do |config|
    config.dsn = 'https://foo:bar@app.getsentry.com/1234'
  end
when 'development'
  class Raven
    def self.capture_message(*)
    end

    def self.capture_exception(*)
    end

    def self.capture(*)
      yield if block_given?
    end
  end
end
```

Combined with code like this in controllers to make debugging in development easier while still ensuring proper behavior in production:
```ruby
def create
  # ...
rescue => e
  if Rails.env.production?
    Raven.capture_exception e, extra: omniauth
    redirect_to :back, flash: {error: e.message}
  else
    raise
  end
end

**Comment by vdaubry** [comment]
Thanks for your detailed answer !

So i'll just disable sentry in development, you can close this issue.

**Comment by nateberkopec** [comment]
Raven should work in any environment. I'll take a look at the problem with web-console.

**Comment by robmadole** [comment]
I'm also having a similar problem but not with web_console.

[Gemfile.lock](https://gist.github.com/robmadole/b96cbd85243e3bd4b25d)
[Backtrace](https://gist.github.com/robmadole/606c7d166ad06a8d6407)

**Comment by bensheldon** [comment]
I'm experiencing the exact same issue when updating from `v0.15.3` to `v0.15.5`.

**Comment by nateberkopec** [comment]
Will push @eugeneius fix out in a release soon :+1:
