### ISSUE TITLE
Unexpected errors caused by Raven after upgrade to 0.14.0+

### ISSUE THREAD

**Issue by ragesoss** [getsentry/raven-ruby#372]
After attempting to upgrade to Raven 0.15.2, several related errors appeared in my specs.

One of the them is `undefined method 'data' for #<Raven::Event:0x00000004874ca0>`, which gets thrown when the program calls .data on an API response object.

The others look like this:
```
TypeError:
       no implicit conversion of Raven::Event into String
     # /home/sage/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `initialize'
     # /home/sage/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `new'
     # /home/sage/.rvm/gems/ruby-2.1.5/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
```
It seems like Raven is taking over errors in gems that would otherwise be handled within the gem?

These issues appear in releases after 0.14.0. Downgrading to 0.13.3 resolved them for me.

**Comment by nateberkopec** [comment]
>  which gets thrown when the program calls .data on an API response object

I'm going to need some more context here. Any background on how to reproduce?

**Comment by ragesoss** [comment]
Here's the spec where I run into it: https://github.com/WikiEducationFoundation/WikiEduDashboard/blob/master/spec/lib/commons_spec.rb#L151

```
  1) Commons.api_get should handle typical network errors
     Failure/Error: results = response.data['pages']
     
     NoMethodError:
       undefined method `data' for #<Raven::Event:0x0000000cbf4b20>
     # ./lib/commons.rb:57:in `get_image_data'
     # ./lib/commons.rb:43:in `get_urls'
     # ./spec/lib/commons_spec.rb:157:in `block (3 levels) in <top (required)>'
```

What's going on is that I'm testing my app's handling of a 503 error that might happen when the `mediawiki_api` gem makes an API call. It looks like Raven has substituted a Raven::Event object in place of the expected (and handled) error that the `mediawiki_api` gem will normally throw after hitting a 503.

**Comment by nateberkopec** [comment]
Weird. Alright, I'll take a look - thanks for the report!

**Comment by nateberkopec** [comment]
I do not believe this is an issue in `raven-ruby`. If you can provide a smaller app that reproduces the issue, I can take another look.

**Comment by ragesoss** [comment]
The root cause might be somewhere else, but it doesn't happen on 0.13.3 or earlier.

**Comment by nateberkopec** [comment]
@ragesoss I understand that, but we change things between versions. We may be returning a Raven::Event object where `nil` was returned before - this isn't necessarily a bug, just something your code didn't expect. Your application is pretty complex and I can't debug it for you.

**Comment by ragesoss** [comment]
Yeah, no problem. Just trying to clarify, in case someone else runs into a similar issue and decides to dig deeper.

**Comment by ragesoss** [comment]
@nateberkopec I think I got it! It was just what you said about a Raven::Event when there used to be a nil. We were capturing some types of exceptions in a rescue clause, and the change from nil to a Raven::Event object meant that it propagated in ways it didn't before. Thanks!

**Comment by nateberkopec** [comment]
@ragesoss :+1: Sorry about that. As a "pre-release" gem we're still changing interfaces from time to time.
